### ISSUE TITLE
Problem deserializing JSON payload with `Optional` fields

### ISSUE THREAD

**Issue by dminkovsky** [google/FreeBuilder#166]
Hi!

I am trying to use FreeBuilder with Jackson per the [README instructions](https://github.com/google/FreeBuilder#jackson) with `Optional` fields, but to no avail. 

Here's my value class:

```
@FreeBuilder
@JsonDeserialize(builder = GraphQLRequestPayload.Builder.class)
public interface GraphQLRequestPayload {

    class Builder extends GraphQLRequestPayload_Builder {}

    Optional<String> getQuery();

    Optional<Map<String, Object>> getVariables();
}
```

Here's the JSON:

```
{"query":"query Index {\n  session {\n    ...F0\n  }\n}\nfragment F0 on Session {\n  id,\n  created\n}","variables":{}}
```

Here's the deserialization code:

```
GraphQLRequestPayload requestPayload;
try {
    requestPayload = JSON_OBJECT_MAPPER.readValue(request.getBody().toByteArray(), GraphQLRequestPayload.class);
} catch (IOException error) {
    // handled
}
```

And the resulting error:

```
streams_1    | com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class java.util.Optional<java.lang.String>] from String value ('query Index {
streams_1    |   session {
streams_1    |     ...F0
streams_1    |   }
streams_1    | }
streams_1    | fragment F0 on Session {
streams_1    |   id,
streams_1    |   created
streams_1    | }'); no single-String constructor/factory method
streams_1    |  at [Source: [B@642ed413; line: 1, column: 2] (through reference chain: pony.services.Builder["query"])
streams_1    |  at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
streams_1    |  at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:878)
streams_1    |  at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:281)
streams_1    |  at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:284)
streams_1    |  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1176)
streams_1    |  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:145)
streams_1    |  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
streams_1    |  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
streams_1    |  at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:107)
streams_1    |  at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:255)
streams_1    |  at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:145)
streams_1    |  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
streams_1    |  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2819)
```

Now, when I change the value class to:

```
@FreeBuilder
@JsonDeserialize(builder = GraphQLRequestPayload.Builder.class)
public interface GraphQLRequestPayload {

    class Builder extends GraphQLRequestPayload_Builder {}

    String getQuery();

    Map<String, Object> getVariables();
}
```

the deserialization happens without any problems. However, now I am not using optional. The semantics of the `variables` field is that it is actually optional. And further, I'd like to use `Optional` for the forced null check.

Anyway, given the error (`no single-String constructor/factory method`), I think perhaps this might be related to how the Jackson and `Optional` compatibility are implemented in FreeBuilder?

Thank you.

**Comment by dminkovsky** [comment]
Oh maybe I didn't Google enough: https://github.com/FasterXML/jackson-datatype-jdk8. Will report back.

**Comment by dminkovsky** [comment]
Yup! https://github.com/FasterXML/jackson-datatype-jdk8 is the solution.

**Comment by chrisalice** [comment]
Thanks, Dmitry! I'll put that link in the README.

**Comment by dminkovsky** [comment]
Thanks for this project!
