### ISSUE TITLE
Failure for @GwtCompatible(serializable = true) class when containing a Multiset

### ISSUE THREAD

**Issue by aabdagic** [google/FreeBuilder#231]
For example:
```java
@FreeBuilder
@GwtCompatible(serializable = true)
public abstract class Foo {

  public abstract ImmutableMultiset<String> getBar();

  static class Builder extends Foo_Builder {}
}
```
fails with:
```
java.util.MissingFormatArgumentException: Format specifier '%s'
[...]
at org.inferred.freebuilder.processor.util.SourceStringBuilder.add(SourceStringBuilder.java:70)
at org.inferred.freebuilder.processor.util.SourceStringBuilder.addLine(SourceStringBuilder.java:76)
at org.inferred.freebuilder.processor.MultisetPropertyFactory$CodeGenerator.addSetFromResult(MultisetPropertyFactory.java:383)
at org.inferred.freebuilder.processor.GwtSupport$CustomValueSerializerExcerpt.addTo(GwtSupport.java:112)
at org.inferred.freebuilder.processor.util.SourceStringBuilder.add(SourceStringBuilder.java:60)
at org.inferred.freebuilder.processor.util.CompilationUnitBuilder.add(CompilationUnitBuilder.java:73)
at org.inferred.freebuilder.processor.CodeGenerator.writeBuilderSource(CodeGenerator.java:86)
at org.inferred.freebuilder.processor.Processor.process(Processor.java:104)
[...]
```
Looking at [the generator][1], it seems like there is one too many %s in the format string there.

[1]:https://github.com/google/FreeBuilder/blob/28591b548edba0ac280afb610b08b13ebc011f9f/src/main/java/org/inferred/freebuilder/processor/MultisetPropertyFactory.java#L383

**Comment by chrisalice** [comment]
This should be fixed as of [https://github.com/google/FreeBuilder/releases/tag/v1.13](v1.13). Apologies for the delay! In retrospect, I should have fixed this first as a point release, but I wasn't expecting #225 to take quite so long in review 😞
